--Library identifiers
LFDB_LIB_IDENTIFIER = "LibFoodDrinkBuff"
LFDB_LIB_IDENTIFIER_SHORT = "LibFDB"

-- Assure that library was not loaded yet?
assert(LIB_FOOD_DRINK_BUFF == nil, string.format("Library \'%s\' was already loaded. Some things might not work properly.", LFDB_LIB_IDENTIFIER))


---------------
-- LANGUAGES --
---------------
LFDB_LANGUAGE_ENGLISH = "en"
LFDB_LANGUAGE_GERMAN = "de"
LFDB_LANGUAGE_FRENCH = "fr"

----------------------------------------------------
-- BUFF TYPES - LibFoodDrinkBuff_buffTypeConstant --
----------------------------------------------------
-- Base value constants
LFDB_BUFF_TYPE_NONE = 0
LFDB_BUFF_TYPE_MAX_HEALTH = 1
LFDB_BUFF_TYPE_MAX_MAGICKA = 2
LFDB_BUFF_TYPE_MAX_STAMINA = 4
LFDB_BUFF_TYPE_REGEN_HEALTH = 8
LFDB_BUFF_TYPE_REGEN_MAGICKA = 16
LFDB_BUFF_TYPE_REGEN_STAMINA = 32
LFDB_BUFF_TYPE_SPECIAL_VAMPIRE = 64
LFDB_BUFF_TYPE_FIND_FISHES = 128
LFDB_BUFF_TYPE_WEREWOLF_TRANSFORMATION = 256

-- Calculated constants based on the base values
LFDB_BUFF_TYPE_MAX_ALL = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_MAX_STAMINA
LFDB_BUFF_TYPE_MAX_ALL_REGEN_HEALTH = LFDB_BUFF_TYPE_MAX_ALL + LFDB_BUFF_TYPE_REGEN_HEALTH
LFDB_BUFF_TYPE_MAX_HEALTH_MAGICKA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA
LFDB_BUFF_TYPE_MAX_HEALTH_MAGICKA_FISH = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_FIND_FISHES
LFDB_BUFF_TYPE_MAX_HEALTH_MAGICKA_REGEN_HEALTH_MAGICKA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_REGEN_MAGICKA
LFDB_BUFF_TYPE_MAX_HEALTH_MAGICKA_REGEN_MAGICKA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_REGEN_MAGICKA
LFDB_BUFF_TYPE_MAX_HEALTH_MAGICKA_SPECIAL_VAMPIRE = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_SPECIAL_VAMPIRE
LFDB_BUFF_TYPE_MAX_HEALTH_REGEN_ALL = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_REGEN_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA
LFDB_BUFF_TYPE_MAX_HEALTH_REGEN_HEALTH = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_HEALTH
LFDB_BUFF_TYPE_MAX_HEALTH_REGEN_MAGICKA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_MAGICKA
LFDB_BUFF_TYPE_MAX_HEALTH_REGEN_STAMINA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_STAMINA
LFDB_BUFF_TYPE_MAX_HEALTH_REGEN_MAGICKA_STAMINA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA
LFDB_BUFF_TYPE_MAX_HEALTH_STAMINA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_STAMINA
LFDB_BUFF_TYPE_MAX_HEALTH_STAMINA_REGEN_HEALTH_STAMINA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_MAX_STAMINA + LFDB_BUFF_TYPE_REGEN_STAMINA
LFDB_BUFF_TYPE_MAX_HEALTH_STAMINA_WEREWOLF = LFDB_BUFF_TYPE_MAX_HEALTH_STAMINA + LFDB_BUFF_TYPE_WEREWOLF_TRANSFORMATION
LFDB_BUFF_TYPE_MAX_MAGICKA_REGEN_HEALTH = LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_REGEN_HEALTH
LFDB_BUFF_TYPE_MAX_MAGICKA_REGEN_MAGICKA = LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_REGEN_MAGICKA
LFDB_BUFF_TYPE_MAX_MAGICKA_REGEN_STAMINA = LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA
LFDB_BUFF_TYPE_MAX_MAGICKA_STAMINA = LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_MAX_STAMINA
LFDB_BUFF_TYPE_MAX_STAMINA_HEALTH_REGEN_STAMINA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_STAMINA + LFDB_BUFF_TYPE_REGEN_STAMINA
LFDB_BUFF_TYPE_MAX_STAMINA_REGEN_HEALTH = LFDB_BUFF_TYPE_MAX_STAMINA + LFDB_BUFF_TYPE_REGEN_HEALTH
LFDB_BUFF_TYPE_MAX_STAMINA_REGEN_MAGICKA = LFDB_BUFF_TYPE_MAX_STAMINA + LFDB_BUFF_TYPE_REGEN_MAGICKA
LFDB_BUFF_TYPE_MAX_STAMINA_REGEN_STAMINA = LFDB_BUFF_TYPE_MAX_STAMINA + LFDB_BUFF_TYPE_REGEN_STAMINA
LFDB_BUFF_TYPE_REGEN_ALL = LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_REGEN_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA
LFDB_BUFF_TYPE_REGEN_HEALTH_MAGICKA = LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_REGEN_MAGICKA
LFDB_BUFF_TYPE_REGEN_HEALTH_STAMINA = LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_REGEN_STAMINA
LFDB_BUFF_TYPE_REGEN_MAGICKA_STAMINA = LFDB_BUFF_TYPE_REGEN_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA
LFDB_BUFF_TYPE_REGEN_MAGICKA_STAMINA_FISH = LFDB_BUFF_TYPE_REGEN_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA + LFDB_BUFF_TYPE_FIND_FISHES
