LFDB_LIB_IDENTIFIER = "LibFoodDrinkBuff"
LFDB_LIB_IDENTIFIER_SHORT = "LibFDB"

local constants

function LibFoodDrinkBuff_InitializeConstants(lib)
	constants = lib

	-----------------
	-- CHAT SYSTEM --
	-----------------
	constants.chat = { }
	if LibChatMessage then
		constants.chat = LibChatMessage(LFDB_LIB_IDENTIFIER, LFDB_LIB_IDENTIFIER_SHORT)
	end
	if not constants.chat.Print then
		constants.chat.Print = function(self, message) df("[%s] %s", LFDB_LIB_IDENTIFIER, message) end
	end

	-------------------------
	-- SUPPORTED LANGUAGES --
	-------------------------
	LFDB_LANGUAGE_ENGLISH = "en"
	LFDB_LANGUAGE_GERMAN = "de"
	LFDB_LANGUAGE_FRENCH = "fr"

	constants.LANGUAGES_SUPPORTED =
	{
		[LFDB_LANGUAGE_ENGLISH] = true,
		[LFDB_LANGUAGE_GERMAN] = true,
		[LFDB_LANGUAGE_FRENCH] = true,
	}

	constants.BLACKLIST_STRING_PATTERN =
	{
		[LFDB_LANGUAGE_ENGLISH] = { "Soul Summons", "Experience", "EXP Buff", "Pelinal", "MillionHealth", "Ambrosia" },
		[LFDB_LANGUAGE_GERMAN] = { "Seelenbeschwörung", "Erfahrungs", "Pelinal", "MillionHealth", "Ambrosia" },
		[LFDB_LANGUAGE_FRENCH] = { "Invocation d'âme", "Expérience", "Bonus EXP", "Pélinal", "MillionHealth", "Ambroisie" },
	}

	local language = GetCVar("language.2")
	constants.clientLanguage = constants.LANGUAGES_SUPPORTED[language] and language or LFDB_LANGUAGE_ENGLISH

	--Check if a string contains a blacklisted pattern
	function constants:DoesStringContainsBlacklistPattern(text)
		local patternFound
		local blacklistStringPattern = constants.BLACKLIST_STRING_PATTERN[constants.clientLanguage]
		for index, pattern in ipairs(blacklistStringPattern) do
			patternFound = text:lower():find(pattern:lower())
			if patternFound then
				return true
			end
		end
		return false
	end

	----------------------------------------------------
	-- BUFF TYPES - LibFoodDrinkBuff_buffTypeConstant --
	----------------------------------------------------
	LFDB_BUFF_TYPE_NONE = 0
	LFDB_BUFF_TYPE_MAX_HEALTH = 1
	LFDB_BUFF_TYPE_MAX_MAGICKA = 2
	LFDB_BUFF_TYPE_MAX_STAMINA = 4
	LFDB_BUFF_TYPE_REGEN_HEALTH = 8
	LFDB_BUFF_TYPE_REGEN_MAGICKA = 16
	LFDB_BUFF_TYPE_REGEN_STAMINA = 32
	LFDB_BUFF_TYPE_SPECIAL_VAMPIRE = 64
	LFDB_BUFF_TYPE_FIND_FISHES = 128
	LFDB_BUFF_TYPE_WEREWOLF_TRANSFORMATION = 256
	LFDB_BUFF_TYPE_MAX_ALL = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_MAX_STAMINA
	LFDB_BUFF_TYPE_MAX_ALL_REGEN_HEALTH = LFDB_BUFF_TYPE_MAX_ALL + LFDB_BUFF_TYPE_REGEN_HEALTH
	LFDB_BUFF_TYPE_MAX_HEALTH_MAGICKA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA
	LFDB_BUFF_TYPE_MAX_HEALTH_MAGICKA_FISH = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_FIND_FISHES
	LFDB_BUFF_TYPE_MAX_HEALTH_MAGICKA_REGEN_HEALTH_MAGICKA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_REGEN_MAGICKA
	LFDB_BUFF_TYPE_MAX_HEALTH_MAGICKA_REGEN_MAGICKA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_REGEN_MAGICKA
	LFDB_BUFF_TYPE_MAX_HEALTH_MAGICKA_SPECIAL_VAMPIRE = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_SPECIAL_VAMPIRE
	LFDB_BUFF_TYPE_MAX_HEALTH_REGEN_ALL = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_REGEN_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA
	LFDB_BUFF_TYPE_MAX_HEALTH_REGEN_HEALTH = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_HEALTH
	LFDB_BUFF_TYPE_MAX_HEALTH_REGEN_MAGICKA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_MAGICKA
	LFDB_BUFF_TYPE_MAX_HEALTH_REGEN_STAMINA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_STAMINA
	LFDB_BUFF_TYPE_MAX_HEALTH_REGEN_MAGICKA_STAMINA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA
	LFDB_BUFF_TYPE_MAX_HEALTH_STAMINA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_STAMINA
	LFDB_BUFF_TYPE_MAX_HEALTH_STAMINA_REGEN_HEALTH_STAMINA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_MAX_STAMINA + LFDB_BUFF_TYPE_REGEN_STAMINA
	LFDB_BUFF_TYPE_MAX_HEALTH_STAMINA_WEREWOLF = LFDB_BUFF_TYPE_MAX_HEALTH_STAMINA + LFDB_BUFF_TYPE_WEREWOLF_TRANSFORMATION
	LFDB_BUFF_TYPE_MAX_MAGICKA_REGEN_HEALTH = LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_REGEN_HEALTH
	LFDB_BUFF_TYPE_MAX_MAGICKA_REGEN_MAGICKA = LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_REGEN_MAGICKA
	LFDB_BUFF_TYPE_MAX_MAGICKA_REGEN_STAMINA = LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA
	LFDB_BUFF_TYPE_MAX_MAGICKA_STAMINA = LFDB_BUFF_TYPE_MAX_MAGICKA + LFDB_BUFF_TYPE_MAX_STAMINA
	LFDB_BUFF_TYPE_MAX_STAMINA_HEALTH_REGEN_STAMINA = LFDB_BUFF_TYPE_MAX_HEALTH + LFDB_BUFF_TYPE_MAX_STAMINA + LFDB_BUFF_TYPE_REGEN_STAMINA
	LFDB_BUFF_TYPE_MAX_STAMINA_REGEN_HEALTH = LFDB_BUFF_TYPE_MAX_STAMINA + LFDB_BUFF_TYPE_REGEN_HEALTH
	LFDB_BUFF_TYPE_MAX_STAMINA_REGEN_MAGICKA = LFDB_BUFF_TYPE_MAX_STAMINA + LFDB_BUFF_TYPE_REGEN_MAGICKA
	LFDB_BUFF_TYPE_MAX_STAMINA_REGEN_STAMINA = LFDB_BUFF_TYPE_MAX_STAMINA + LFDB_BUFF_TYPE_REGEN_STAMINA
	LFDB_BUFF_TYPE_REGEN_ALL = LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_REGEN_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA
	LFDB_BUFF_TYPE_REGEN_HEALTH_MAGICKA = LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_REGEN_MAGICKA
	LFDB_BUFF_TYPE_REGEN_HEALTH_STAMINA = LFDB_BUFF_TYPE_REGEN_HEALTH + LFDB_BUFF_TYPE_REGEN_STAMINA
	LFDB_BUFF_TYPE_REGEN_MAGICKA_STAMINA = LFDB_BUFF_TYPE_REGEN_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA
	LFDB_BUFF_TYPE_REGEN_MAGICKA_STAMINA_FISH = LFDB_BUFF_TYPE_REGEN_MAGICKA + LFDB_BUFF_TYPE_REGEN_STAMINA + LFDB_BUFF_TYPE_FIND_FISHES

	--Get the ability's buffType (food or drink)
	function constants:GetBuffTypeInfos(abilityId)
	-- Returns 2: number buffTypeFoodDrink, bool isDrink
		local drinkBuffType = constants.DRINK_BUFF_ABILITIES[abilityId]
		if drinkBuffType then
			return drinkBuffType, true
		end
		local foodBuffType = constants.FOOD_BUFF_ABILITIES[abilityId]
		if foodBuffType then
			return foodBuffType, false
		end
		return LFDB_BUFF_TYPE_NONE, nil -- LFDB_BUFF_TYPE_NONE = 0
	end

	LibFoodDrinkBuff_InitializeConstants = nil
end